### PR TITLE
Further API additions and CLI tooling for hapy-heritrix

### PR DESCRIPTION
**Pull request by anjackson**
We've started using `hapy-heritrix` and have been extending it with some additional functionality. As well as adding to the API, we've also added a command-line tool and some more console scripts. It would be helpful to us if this code was in an official `hapy-heritrix` release.

The pull request is just to see if you are interested in these additions?

### CODE REVIEW

**Comment by WilliamMayor** [comment]
Wow! I had no idea that this project was of interest to anyone. I dread to think how bad the code looks :)

I'm more than happy to merge if doing so would be useful to someone? I'm also more than happy to pass this project over to a new lead dev? I've no idea if that would be helpful?

Thanks for the PR at any rate :)

**Comment by WilliamMayor** [comment]
Hi @anjackson, I just got a notification that this PR had been updated. Looking over it I think that it contains some private data? Passwords and URLs that you're using internally?

I'm still happy to transfer control of this repo and the PyPI account to you if you're doing active development on this? I don't really have the time or knowledge to meaningfully review and accept PRs.

**Comment by anjackson** [comment]
Thanks for checking with me! It's all just test data/environment information, so that's not a big problem.

I'm not quite in a position to take on owning this yet, so I'll just close this pull for now. Sorry for the bother!

**Comment by WilliamMayor** [comment]
No worries, and no bother! Let me know if you change your mind :)

**Pull request closed without merging**
